apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-kafka
  labels:
    app: spring-boot-kafka
spec:
  nodeName: minikube
  containers:
    - name: spring-boot-kafka
      # get latest version of image
      image: spring-boot-kafka
      imagePullPolicy: IfNotPresent
      ports:
        # containerPort is the port exposed by the container
        - containerPort: 9000
