apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-service
  name: spring-boot-service
spec:
  ports:
    # The port that this service should serve on.
    - port: 9000
      targetPort: 9000
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: spring-boot-kafka
  type: NodePort